### ISSUE TITLE
Align the projects in the projects page with either the sort order or with the logo

### ISSUE THREAD

**Issue by mnltejaswini** [bharadwajduggaraju/Jagathi-Foundation#16]

**Comment by mnltejaswini** [comment]
@media (min-width: 1024px)
.lg\:ml-16 {
    margin-left: 10.5rem;
}


@media (min-width: 1024px)
.lg\:mr-16 {
    margin-right: 11rem;
}

**Comment by bharadwajduggaraju** [comment]
im closing this as it doesnt look good
